application: apprtc
version: 4
runtime: python
api_version: 1

handlers:
- url: /html
  static_dir: html

- url: /images
  static_dir: images 

- url: /js
  static_dir: js

- url: /vendor
  static_dir: vendor

- url: /models
  static_dir: models

- url: /.*
  script: apprtc.py
  secure: always
  
inbound_services:
- channel_presence
